modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/wisp-forest/lavender/issues"
license = "MIT"

[[mods]]
modId = "lavender_flower"
version = "1.0"
displayName = "Lavender Flower"
authors = "glisco"
displayURL = "https://modrinth.com/project/lavender"
description = '''
Lavender Testmod
'''


[[dependencies.lavender_flower]]
modId = "neoforge"
required = true
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lavender_flower]]
modId = "minecraft"
required = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lavender_flower]]
modId = "owo"
required = true
versionRange = "[0.12.10,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lavender_flower]]
modId = "lavender"
required = true
ordering = "NONE"
side = "BOTH"